### ISSUE TITLE
On Symfony 5 - wrong return value for StartWorkerCommand::execute()

### ISSUE THREAD

**Issue by ugo-fl** [resquebundle/resque#58]
When running : `php bin/console resque:worker-start "*" --verbose`

I get the following :
```
Starting worker nohup /usr/bin/php7.4  /var/www/symfony/vendor/resquebundle/resque/Command/../bin/resque > /var/www/symfony/var/log/resque.log 2>&1 & echo $!
Worker started 8315b23b7b85:217:*

In Command.php line 261:
                                                                                                                         
  [TypeError]                                                                                                            
  Return value of "ResqueBundle\Resque\Command\StartWorkerCommand::execute()" must be of the type int, "null" returned.  
                                                                                                                         

Exception trace:
  at /var/www/symfony/vendor/symfony/console/Command/Command.php:261
 Symfony\Component\Console\Command\Command->run() at /var/www/symfony/vendor/symfony/console/Application.php:938
 Symfony\Component\Console\Application->doRunCommand() at /var/www/symfony/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/symfony/vendor/symfony/console/Application.php:266
 Symfony\Component\Console\Application->doRun() at /var/www/symfony/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/symfony/vendor/symfony/console/Application.php:142
 Symfony\Component\Console\Application->run() at /var/www/symfony/bin/console:43

resque:worker-start [-c|--count COUNT] [-i|--interval INTERVAL] [-f|--foreground] [-m|--memory-limit MEMORY-LIMIT] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <queues>
```

**Comment by PhilETaylor** [comment]
yup Ive seen these, this is actually 2 errors. 

1) Commands now need to return an int https://symfony.com/blog/new-in-symfony-4-4-console-improvements

2) If a job throws an error now, it seems to throw TypeError and not Exception in later PHP versions 

Im upgrading my largest project to PHP 8.0.0 and Symfony 5.2.0 this month and up until Christmas so as soon as I get to the worker layer of my code I'll be digging deeper into these issues.

**Comment by quentint** [comment]
Hey, any update on this?  
Thanks!

**Comment by PhilETaylor** [comment]
fixed in https://github.com/resquebundle/resque/releases/tag/4.1.1 

Im about to tag and release a 5.0.0 release too which is targeted at Symfony 5.3 and PHP 8 onwards.

**Comment by quentint** [comment]
Great, thanks!  
Will this new release be compatible with PHP 7, or only 8+?

**Comment by PhilETaylor** [comment]
Anything in the 4.x series should be compatible with PHP 7, so 4.1.1 should be compatible with PHP 7

Anything in the (just now released) 5.x series is targeted at PHP 8+ and Symfony 5.3.1+ only.  

Both releases were just made.

**Comment by quentint** [comment]
Both thumbs up. Thanks!

**Comment by quentint** [comment]
Oh, and I notice the second issue of your first comment is still happening, right?

I get this error:

```
#2 /app/vendor/resque/php-resque/lib/Resque/Worker.php(312): Resque_Job->fail(Object(Error))
#3 /app/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#4 /app/vendor/resquebundle/resque/bin/resque(178): Resque_Worker->work('5', false)
#5 {main}
  thrown in /app/vendor/resquebundle/resque/bin/resque on line 109
Symfony\Component\ErrorHandler\Error\FatalError {#3735
  -error: array:4 [
    "type" => 1
    "message" => """
      Uncaught TypeError: Argument 1 passed to {closure}() must be an instance of Exception, instance of Error given, called in /app/vendor/resque/php-resque/lib/Resque/Event.php on line 37 and defined in /app/vendor/resquebundle/resque/bin/resque:109\n
      Stack trace:\n
      #0 /app/vendor/resque/php-resque/lib/Resque/Event.php(37): {closure}(Object(Error), Object(Resque_Job))\n
      #1 /app/vendor/resque/php-resque/lib/Resque/Job.php(226): Resque_Event::trigger('onFailure', Array)\n
      #2 /app/vendor/resque/php-resque/lib/Resque/Worker.php(312): Resque_Job->fail(Object(Error))\n
      #3 /app/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))\n
      #4 /app/vendor/resquebundle/resque/bin/resque(178): Resque_Worker->work('5', false)\n
      #5 {main}\n
        thrown
      """
    "file" => "/app/vendor/resquebundle/resque/bin/resque"
    "line" => 109
  ]
```

Can you help me with that?  
Thanks 😉

**Comment by PhilETaylor** [comment]
I thought that was fixed in the 5.0.0 release? 

https://github.com/resquebundle/resque/blob/45de899fbe2905801508e6315c7fa98175ebdb0d/bin/resque#L109

**Comment by quentint** [comment]
It is; but not in the `4.1.1`, which I'm using (I'm still on PHP 7.x).

**Comment by PhilETaylor** [comment]
```php
Error | Exception $exception
```

Union types is a PHP 8 feature only :-( 

I'll take another look today. I was confused why the worker started raising `Error` and not `Exception` anyway as Im pretty sure I have not changed that :)

**Comment by PhilETaylor** [comment]
ok so on testing this the only thing we can do is remove the type hint as the upstream Rescue lib can create an `Error` or `Exception` 

This looks to have changed when PHP 7 [changes were made](https://github.com/resque/php-resque/commit/f993b9f5dbf230149e51c6891531e9f0eaa59619) upstream. but that was 2016 and none of us (I assume more than just you and I use this project?) were effected by the changes haha

I'll remove the typehint and release the 4.1.2 in a moment

**Comment by quentint** [comment]
Yup, looks good to me :)

**Comment by PhilETaylor** [comment]
Release done

**Comment by quentint** [comment]
You rock. Thanks!
